name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Dar permisos a gradlew
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x java/gradlew
        
      - name: Update property
        path: java
        shell: pwsh
        run: |
          $file = "gradle.properties"
          $key = "projectVersion"
          $newValue = ${GITHUB_REF_NAME#v}

          (Get-Content $file) |
            ForEach-Object {
              if ($_ -match "^$key=") {
                "$key=$newValue"
              } else {
                $_
              }
            } |
            Set-Content $file
      
      - name: Commit and push changes
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git status
          git add config.properties

          if (git diff --cached --quiet) {
            Write-Host "No changes to commit"
          } else {
            git commit -m "Release, update projectVersion in gradle.properties"
            git push
          }
        
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        working-directory: java
        run: .\gradlew.bat lwjgl3:laffDistWindows --no-daemon --console=plain --info

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: java
        run: ./gradlew lwjgl3:laffDistLinux --no-daemon --console=plain --info

      - name: Empaquetar artefactos
        working-directory: java
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mkdir "tmp"
            ZIP_NAME="tmp\Charnego Internatiolaff Soccer (win64 ${GITHUB_REF_NAME#v}).zip"
            powershell Compress-Archive -Path "lwjgl3\build\libs\*" -DestinationPath "$ZIP_NAME"
            echo "ARTIFACT=Charnego Internatiolaff Soccer" >> $GITHUB_OUTPUT
          else
            mkdir -p "tmp"
            TAR_NAME="tmp/Charnego Internatiolaff Soccer (linux64 ${GITHUB_REF_NAME#v}).tar.gz"
            mkdir -p "tmp"
            cp -r lwjgl3/build/libs/* "tartmp/"
            tar -czf "$TAR_NAME" "tartmp"
            echo "ARTIFACT=Charnego Internatiolaff Soccer" >> $GITHUB_OUTPUT
          fi

      - name: Crear GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Release autom√°tica de ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir artefactos a la release
        uses: softprops/action-gh-release@v1
        with:
          files: java/tmp/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}